### ISSUE TITLE
TaskManager comparator needs 'const' for GCC 16+ compatibility

### ISSUE THREAD

**Issue by Hemanthkumarmd** [deniskropp/DirectFB#29]
## Description

DirectFB 1.7.7 fails to build with GCC 16 (tested with GCC 16.1.0) due to a non-const comparator used with `std::set`.

Recent libstdc++ versions perform stricter checks on associative container comparators and require them to be invocable on a `const` comparator object. The comparator defined in `TaskManager` does not satisfy this requirement, causing the build to fail.

## To Reproduce

Build DirectFB 1.7.7 with GCC 16.

## Build Output

```cpp
/usr/include/c++/16/bits/stl_tree.h:1402:72: error: static assertion failed:
comparison object must be invocable with arguments of key_type
 1402 | __is_invocable<const _Compare&, const _Key&, const _Key&>::value,
      |                                                                        ^~~~~

/usr/include/c++/16/bits/stl_tree.h:1406:40: error: no match for call to
'(const DirectFB::TaskManager) (DirectFB::Task* const&, DirectFB::Task* const&)'
 1406 | return _M_impl._M_key_compare(__k1, __k2);
      |        ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~

In file included from src/core/TaskManager.cpp:58:
src/core/TaskManager.h:124:11:
  124 | bool operator()( Task *t1, Task *t2 )
      |           ^~~~~~~~
```

## Expected behavior

DirectFB should build successfully with GCC 16 and newer libstdc++ versions.

## Root Cause

`TaskManager` is used as a comparator for a `std::set`, but its comparison operator is not `const` qualified:

```cpp
bool operator()( Task *t1, Task *t2 )
{
    return t1->ts_emit < t2->ts_emit;
}
```

Since the comparator does not modify any state, it should be callable on a const object.

## Proposed Fix

```diff
--- a/src/core/TaskManager.h
+++ b/src/core/TaskManager.h
@@ -121,7 +121,7 @@ public:
      static void dumpTasks();

-     bool operator()( Task *t1, Task *t2 )
+     bool operator()( Task *t1, Task *t2 ) const
      {
           return t1->ts_emit < t2->ts_emit;
      }
```

## Verification

Applying the above change resolves the build failure and allows DirectFB 1.7.7 to build successfully with GCC 16.1.0.

## Environment

- DirectFB: 1.7.7
- GCC: 16.1.0
- libstdc++: 16.1.0
